env: "local" # local, prod
maigration_folder: "../../internal/migrator/migrations" # папка с миграциями
grpc:
  port: 44441
database:
  user: "postgres"
  password: "123"
  host: "localhost"
  table: "eds"
  request_timeout: 5
