env: "local" # local, prod
maigration_folder: "../../migrations" # папка с миграциями
grpc:
  port: 44441 # порт для сервера
database:
  user: "postgres"
  password: "123"
  host: "localhost"
  table: "eds"
  request_timeout: 5
kafka_host: localhost:9092
clients_cfg:
  get_mail_consumer:
    address: "localhost:44441" # подключаемся к серверу grpc
    timeout: 1
    retries_count: 3
