env: "prod" # local, prod
maigration_folder: "./migrations" # папка с миграциями
grpc:
  port: 44441
database:
  user: "postgres"
  password: "123"
  host: db
  table: "eds"
  request_timeout: 5
kafka_host: localhost:9092
clients_cfg:
  get_mail_consumer:
    address: "localhost"
    timeout: 1
    retries_count: 3
